In [13]:
import numpy as np
import matplotlib.pyplot as plt
from nltk.parse.stanford import StanfordParser
import numpy as np

In [14]:

np.__version__

'1.14.0'

In [16]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [17]:
type(x)

numpy.ndarray

In [20]:
m=np.array([[1,2,3],
            [4,7,4],
            [7,8,9]])

In [21]:
print(m)

[[1 2 3]
 [4 7 4]
 [7 8 9]]


In [22]:
print(m.shape)

(3, 3)


In [23]:
m.transpose()

array([[1, 4, 7],
       [2, 7, 8],
       [3, 4, 9]])

In [26]:
np.linalg.det(m)

-36.0

In [27]:
m_inv=np.linalg.inv(m)

In [33]:
m_inv

array([[-0.86111111, -0.16666667,  0.36111111],
       [ 0.22222222,  0.33333333, -0.22222222],
       [ 0.47222222, -0.16666667,  0.02777778]])

In [35]:
iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
m=np.array([[1,2,3],
          [4,7,4],
          [2,0,9]])
eigen_vals,eign_vecs=np.linalg.eig(m)
print(eigen_vals)
print(eign_vecs)

[-0.47722558 10.47722558  7.        ]
[[-0.90436728  0.31364947 -0.21199958]
 [ 0.38170128  0.84929336 -0.95399809]
 [ 0.19085064  0.42464668  0.21199958]]


In [47]:
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])
U,S,VT=np.linalg.svd(m)
print('Getting Svd outputs:\n')
print('U:\n',U,'\n')
print('S:\n',S,'\n')
print('VT:\n',VT,'\n')


Getting Svd outputs:

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



In [48]:
import scipy as sp

In [49]:
import numpy as np

In [50]:
nums=np.random.randint(1,20,size=(1,15))[0]

In [51]:
print(nums)

[18  3 18  5 14  8 11  1 11 10 18 18  1  1 19]


In [52]:
print(sp.mean(nums))

10.4


In [55]:
print(sp.median(nums))

11.0


In [90]:
import pandas as pd
pd.options.mode.chained_assignment=None

df=pd.read_csv('/Users/abhisheksingh/Downloads/student_records.csv')
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [91]:
feature_names=['OverallGrade','Obedient','ResearchScore','ProjectScore']
training_features=df[feature_names]

outcome_name=['Recommend']
outcome_labels=df[outcome_name]
print(training_features)

print(outcome_labels)


  OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33
  Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No


In [92]:
numeric_feature_names=['ResearchScore','ProjectScore']
categorical_feature_names=['OverallGrade','Obedient']


In [93]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

ss.fit(training_features[numeric_feature_names])

training_features[numeric_feature_names]=ss.transform(training_features[numeric_feature_names])

training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

In [94]:
training_features=pd.get_dummies(training_features,columns=categorical_feature_names)
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [100]:
categorical_engineered_features = list(set(training_features.columns)-set(numeric_feature_names))
print(categorical_engineered_features)

['OverallGrade_F', 'Obedient_N', 'OverallGrade_C', 'OverallGrade_B', 'Obedient_Y', 'OverallGrade_E', 'OverallGrade_A']


In [103]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model=lr.fit(training_features,np.array(outcome_labels['Recommend']))
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [110]:
pred_labels=model.predict(training_features)
actual_labels=np.array(outcome_labels)

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print(float(accuracy_score(actual_labels,pred_labels))*100,'%')
print(classification_report(actual_labels,pred_labels))

100.0 %
             precision    recall  f1-score   support

         No       1.00      1.00      1.00         5
        Yes       1.00      1.00      1.00         3

avg / total       1.00      1.00      1.00         8



In [112]:
from sklearn.externals import joblib
import os

if not os.path.exists('Model'):
    os.mkdir('Model')
if not os.path.exists('Scaler'):
    os.mkdir('Scaler')
    
joblib.dump(model, r'Model/model.pickle') 
joblib.dump(ss, r'Scaler/scaler.pickle')   

['Scaler/scaler.pickle']

In [113]:
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')


In [115]:
new_data=pd.DataFrame([{'Name':'Nathan','OverallGrade':'F','Obedient':'N','ResearchScore':30,'ProjectScore':20},
                       {'Name': 'Thomas', 'OverallGrade': 'A', 'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
new_data


Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

In [120]:
prediction_features=new_data[feature_names]
#print(prediction_features)
prediction_features[numeric_feature_names]=scaler.transform(prediction_features[numeric_feature_names])
prediction_features=pd.get_dummies(prediction_features,columns=categorical_feature_names)
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  
0           0  
1           1

In [133]:
current_categorical_engineered_features=set(prediction_features.columns)-set(numeric_feature_names)
print(current_categorical_engineered_features)
missing_features=set(categorical_engineered_features)-set(current_categorical_engineered_features)
print(missing_features)
for feature in missing_features:
    # add zeros since feature is absent in these data samples
    prediction_features[feature] = [0] * len(prediction_features)
    
prediction_features

{'OverallGrade_F', 'Obedient_N', 'OverallGrade_C', 'OverallGrade_B', 'Obedient_Y', 'OverallGrade_E', 'OverallGrade_A'}
set()


ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  OverallGrade_B  OverallGrade_E  OverallGrade_C  
0           0               0               0               0  
1           1               0               0               0

In [134]:
predictions=model.predict(prediction_features)

In [137]:
new_data['Recommend']=predictions
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20        No
1  Thomas            A        Y             78            80       Yes

In [146]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape
arr.dtype


dtype('int64')

In [149]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [153]:
arr=np.random.randn(3,4)
arr

array([[ 0.29390036,  1.18533024, -0.78459286, -0.59858528],
       [-1.561006  , -0.53421671,  0.67794737,  0.24168999],
       [-2.32341113, -1.11480877,  1.42016462,  1.94702711]])

In [151]:
arr=np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")
arr

array([[ 2. , 23. , 33. ],
       [32. , 42. , 63.4],
       [35. , 77. , 12. ]])

In [155]:
arr[1]

array([32. , 42. , 63.4])

In [158]:
arr=np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [161]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [164]:
arr=np.arange(10)
arr[5:]

array([5, 6, 7, 8, 9])

In [166]:
arr[5:8]

array([5, 6, 7])

In [169]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [172]:
arr=np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [174]:
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [178]:
#what the fuck is this??
arr[...,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [182]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [183]:
#what the fuck(2) is this
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

In [184]:
cities=np.array(['d','b','m','c','b'])
city_data=np.random.randn(5,3)
city_data

array([[ 1.75499554,  0.10018196, -0.18376001],
       [ 0.93015444,  0.28263444, -0.72856722],
       [-1.19084702, -1.92934289,  0.10010899],
       [ 0.66117912,  0.32378802, -0.82507652],
       [ 1.21448723,  0.13400223,  0.56310175]])

In [185]:
city_data[cities=='d']


array([[ 1.75499554,  0.10018196, -0.18376001]])

In [186]:
city_data[city_data>0]

array([1.75499554, 0.10018196, 0.93015444, 0.28263444, 0.10010899,
       0.66117912, 0.32378802, 1.21448723, 0.13400223, 0.56310175])

In [195]:
arr=np.arange(15).reshape(3,5)
arr
arr+5
np.modf(arr)

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]), array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]]))

In [197]:
a = np.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
x = np.linalg.solve(a, b)
x

array([1., 3., 2.])

In [200]:
np.allclose(np.dot(a,x),b)

True

In [205]:
import pandas as pd
d=[{'city':'Delhi','data':1000},
   {'city':'Bangalore','data':2000},
   {'city':'Mumbai','data':1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Bangalore  2000
2     Mumbai  1000

In [206]:
df=pd.DataFrame(d)


In [218]:
city_data=pd.read_csv('/Users/abhisheksingh/Downloads/simplemaps-worldcities-basic.csv')

In [220]:
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [222]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [ ]:
series_es=city_data.lat

In [227]:
type(series_es)

pandas.core.series.Series

In [230]:
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [232]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [234]:
series_es[:-7315]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [235]:
city_data[:7]

city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan   
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan   
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan   
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan   
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan   
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan   
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan   

  iso2 iso3 province  
0   AF  AFG  Badghis  
1   AF  AFG     Ghor  
2   AF  AFG  Hilmand  
3   AF  AFG   Nimroz  
4   AF  AFG  Uruzgan  
5   AF  AFG  Paktika  
6   AF  AFG    Kunar

In [241]:
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [242]:
city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop':'population'}, inplace=True)
city_greater_10mil.where(city_greater_10mil.population > 15000000)

city city_ascii        lat         lng  population country iso2 iso3  \
360      NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
1171     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
2068     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3098     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3110  Mumbai     Mumbai  19.016990   72.856989  15834918.0   India   IN  IND   
3492   Tokyo      Tokyo  35.685017  139.751407  22006299.5   Japan   JP  JPN   
4074     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
4513     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
5394     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
6124     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
7071     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   

         province  
360           NaN  
1171          NaN  
2068          NaN  
3098          NaN  
3110  Maharashtra  
3492        Tokyo  
4074          NaN  
4513          NaN  
5394          NaN  
6124          NaN  
7071          NaN

In [247]:
df = pd.DataFrame(np.random.randn(8, 3),columns=['A', 'B', 'C'])

In [250]:
nparray=df.values
type(nparray)

numpy.ndarray

In [253]:
from numpy import nan
df.iloc[4,2]=nan

In [254]:
df

A         B         C
0 -1.130162  1.895059 -0.811175
1 -1.672759  1.756385 -0.693414
2  0.829323  2.058634 -0.727235
3 -1.272007 -1.151737  0.005134
4  0.976148  2.029140       NaN
5 -1.531259 -0.409676  0.783886
6 -1.409983 -2.064072  0.862796
7 -0.327361  1.056162 -1.181153

In [255]:
df.fillna(0)

A         B         C
0 -1.130162  1.895059 -0.811175
1 -1.672759  1.756385 -0.693414
2  0.829323  2.058634 -0.727235
3 -1.272007 -1.151737  0.005134
4  0.976148  2.029140  0.000000
5 -1.531259 -0.409676  0.783886
6 -1.409983 -2.064072  0.862796
7 -0.327361  1.056162 -1.181153

In [259]:
columns_numeric=['lat','lng','pop']
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

In [257]:
city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

In [258]:
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

In [261]:
city_data[columns_numeric].median()

lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64

In [262]:
city_data[columns_numeric].quantile(0.8)

lat        46.852480
lng        89.900018
pop    269210.000000
Name: 0.8, dtype: float64

In [265]:
city_data[columns_numeric].sum(axis=1).head()

0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64